### ISSUE TITLE
Unable to use this extensaion

### ISSUE THREAD

**Issue by googlina** [marcosvrs/WTF#37]
While trying to send message, getting error "Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist."

**Comment by nxwi** [comment]
same here, nothing happens when i click send.

**Comment by Juteenar** [comment]
Having the same issues, send button does nothing

**Comment by emersonferryere** [comment]
A extensão parou de funcionar, quando você clica em enviar nada acontece. :'(

**Comment by Himanshusha673** [comment]
@marcosvrs  please resolve and give us proper feedback on this?
is this issue arised due to loader is not injecting properly or something else?

**Comment by marcosvrs** [comment]
Hi everyone,
Unfortunately, I'm not having some free time these days to have a look into this issue.
Once I have some time, I will update here.

Otherwise, the community can also help us here by providing a PR with the fix ;)

**Comment by PatelBassar** [comment]
Hi,
send button does nothing.Please help

**Comment by javix64** [comment]
@marcosvrs I think this issue is related with wa-js instead of this package.

Also this repository has a simillar issue: https://github.com/pedroslopez/whatsapp-web.js/issues/2789

**Comment by PatelBassar** [comment]
can anyone help me to guide in compiling this source. TIA

**Comment by PatelBassar** [comment]
@marcosvrs you created an amazing thing.i was using it earlier but currently it is not working. kindly help me to compile from source.

**Comment by marcosvrs** [comment]
Hi everyone,

Thank you for your patience and for bringing this issue to my attention. I've managed to resolve it now.

The root of the problem was an old workaround in our code that was initially designed to load `@wppconnect/wa-js` after the main WhatsApp web application had fully loaded.

I have removed this workaround, and now it loads in sync with WhatsApp Web without any additional delays or hooks. This adjustment should restore the functionality.

Please pull the latest changes from the repository or update the extension from Chrome Web Store (Might take some hours to be available) and let me know if you encounter any further issues.

For those looking to compile the source, ensure you have the latest version and follow the standard build steps outlined in our README.

Thank you for your contributions!
